# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPS',
            new_name='BikeGPS',
        ),
        migrations.RenameModel(
            old_name='HistoricalGPS',
            new_name='HistoricalBikeGPS',
        ),
        migrations.AlterModelOptions(
            name='historicalbikegps',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bike gps'},
        ),
    ]
