# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='low_step',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalbike',
            name='low_step',
            field=models.BooleanField(default=False),
        ),
    ]
