# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20160920_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
