# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_auto_20160727_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bike.Fleet'),
        ),
        migrations.AlterField(
            model_name='historicalbike',
            name='fleet',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bike.Fleet'),
        ),
    ]
