# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 21:41
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_auto_20160727_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='operation',
            new_name='operating',
        ),
        migrations.RemoveField(
            model_name='fleet',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='fleet',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=2539663939, max_length=128),
            preserve_default=False,
        ),
    ]
