# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0004_auto_20160727_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsteward',
            name='rank',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='steward',
            name='rank',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
