# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='hired',
        ),
        migrations.AddField(
            model_name='driver',
            name='rank',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
