# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20160727_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='first',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='driver',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
