# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0002_auto_20160914_1345'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterDamage',
            fields=[
                ('damage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Damage')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Shelter')),
            ],
            bases=('maintenance.damage',),
        ),
        migrations.CreateModel(
            name='ShelterInventory',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Inventory')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Shelter')),
            ],
            bases=('maintenance.inventory',),
        ),
        migrations.CreateModel(
            name='ShelterMaintenance',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Maintenance')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Shelter')),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.ShelterDamage')),
            ],
            bases=('maintenance.maintenance',),
        ),
        migrations.CreateModel(
            name='SignDamage',
            fields=[
                ('damage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Damage')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Sign')),
            ],
            bases=('maintenance.damage',),
        ),
        migrations.CreateModel(
            name='SignInventory',
            fields=[
                ('inventory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Inventory')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Sign')),
            ],
            bases=('maintenance.inventory',),
        ),
        migrations.CreateModel(
            name='SignMaintenance',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Maintenance')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Sign')),
                ('damage_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.SignDamage')),
            ],
            bases=('maintenance.maintenance',),
        ),
        migrations.RemoveField(
            model_name='stopdamage',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stopdamage',
            name='damage_ptr',
        ),
        migrations.RemoveField(
            model_name='stopinventory',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stopinventory',
            name='inventory_ptr',
        ),
        migrations.RemoveField(
            model_name='stopmaintenance',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='stopmaintenance',
            name='damage_report',
        ),
        migrations.RemoveField(
            model_name='stopmaintenance',
            name='maintenance_ptr',
        ),
        migrations.DeleteModel(
            name='StopDamage',
        ),
        migrations.DeleteModel(
            name='StopInventory',
        ),
        migrations.DeleteModel(
            name='StopMaintenance',
        ),
    ]
