# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20160914_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='damage',
            field=models.CharField(choices=[('M', '(Minor) damage requires attention but does not impact the operation of the asset.'), ('R', '(Repairable) damage impacts the operation of the asset but can be repaired.'), ('S', '(Scheduled) damage caused by normal operation that needs routine maintenance.'), ('T', '(Totaled) damage which cannot or should not be repaired and renders the asset unusable.'), ('L', '(Loss) loss or theft of asset.')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='damage',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(choices=[('A', '(A) Asset is in inventory but not deployed/distributed.'), ('D', '(D) Asset shows damage. Follow-up with appropriate damage form.'), ('I', '(I) Asset should be inspected by someone trained to assess the asset.'), ('P', '(P) Asset passed inventory level-of-service standards.'), ('S', '(S) Asset should be swapped out with another asset.'), ('U', '(U) Asset is neither in inventory nor deployed/distributed.')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
