# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0001_initial'),
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entry',
            unique_together=set([('metadata', 'time', 'on', 'off')]),
        ),
    ]
