# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Entry',
        ),
    ]
