# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['time', 'off']},
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='driver',
        ),
        migrations.AlterField(
            model_name='entry',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='rider.Metadata'),
        ),
    ]
