# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20160720_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='metadata',
            name='sheet',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
