# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-20 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(max_length=12)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
