# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
