# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
