# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('C', 'Cantilever model.'), ('N', 'Niagra model.')], max_length=1)),
                ('size', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(choices=[('A', '2015 Sign Design - Large Route Circles.'), ('B', '2016 Sign Design - Top Green Stripe, Modular Routes.')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='stop',
            name='shelter',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='signage',
        ),
        migrations.AddField(
            model_name='sign',
            name='stop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stop.Stop'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='stop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stop.Stop'),
        ),
    ]
