# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='max_stop',
            new_name='maximum',
        ),
        migrations.RenameField(
            model_name='geography',
            old_name='min_stop',
            new_name='minimum',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='stop_id',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='geography',
            name='geo_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='connections',
        ),
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='available',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='geography',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(choices=[('A', 'Sign is available but not in the field.'), ('D', 'Sign is damaged but does not require replacement.'), ('F', 'Sign is in a temporary frame.'), ('G', 'Sign is in a temporary frame but the ground has been dug, awaiting post.'), ('I', 'Sign post or anchor requires inspection by JBLM shop.'), ('N', 'Sign was not reviewed.'), ('P', 'Sign is posted and up to standard.'), ('R', 'Sign has sustained damaged and needs to be replaced.'), ('S', 'Sign needs to be swapped due to a pilot or style upgrade.'), ('U', 'Sign needs to be placed but is currently unavailable.')], max_length=1),
        ),
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
