# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0002_auto_20160914_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='design',
            field=models.CharField(choices=[('C', 'Cantilever model.'), ('N', 'Niagara model.'), ('G', 'Gable model.')], max_length=1),
        ),
    ]
