# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0002_auto_20160726_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geography',
            old_name='geography',
            new_name='name',
        ),
    ]
