# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0003_auto_20160914_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='midi_guide',
            field=models.BooleanField(default=False),
        ),
    ]
