# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0004_auto_20160727_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
