# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0005_auto_20160914_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='anchor',
            field=models.CharField(choices=[('G', 'Sign is attached to a ground anchor.'), ('P', 'Sign is attached to a plate anchor.')], default='G', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='location_type',
            field=models.IntegerField(choices=[(0, 'Stop location where passengers board or disembark from a transit vehicle.'), (1, 'Station, physical structure, or area that contains more than one stop.')], default=0),
            preserve_default=False,
        ),
    ]
