# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0006_auto_20160727_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set([('timestamp', 'stop')]),
        ),
    ]
