# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='go_permission',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='transit_staff',
        ),
        migrations.RemoveField(
            model_name='historicalenduser',
            name='go_permission',
        ),
        migrations.RemoveField(
            model_name='historicalenduser',
            name='transit_staff',
        ),
    ]
