# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 23:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_permission', models.IntegerField(default=0)),
                ('transit_staff', models.IntegerField(default=0)),
                ('waiver', models.CharField(blank=True, choices=[('C', "User's waiver is currently up-to-date."), ('E', 'User must sign new waiver agreement.'), ('N', 'User has not signed a waiver.')], max_length=1, null=True)),
                ('waiver_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'The main active bike steward'), ('B', 'A designated back-up steward'), ('I', 'The steward is no longer active')], max_length=1, null=True)),
                ('fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.Fleet')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEndUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('go_permission', models.IntegerField(default=0)),
                ('transit_staff', models.IntegerField(default=0)),
                ('waiver', models.CharField(blank=True, choices=[('C', "User's waiver is currently up-to-date."), ('E', 'User must sign new waiver agreement.'), ('N', 'User has not signed a waiver.')], max_length=1, null=True)),
                ('waiver_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('A', 'The main active bike steward'), ('B', 'A designated back-up steward'), ('I', 'The steward is no longer active')], max_length=1, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fleet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='fleet.Fleet')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical end user',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.RemoveField(
            model_name='cyclist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalcyclist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcyclist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalsteward',
            name='fleet',
        ),
        migrations.RemoveField(
            model_name='historicalsteward',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsteward',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='PTC',
        ),
        migrations.DeleteModel(
            name='Rider',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.RemoveField(
            model_name='steward',
            name='fleet',
        ),
        migrations.RemoveField(
            model_name='steward',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cyclist',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='HistoricalCyclist',
        ),
        migrations.DeleteModel(
            name='HistoricalSteward',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
        migrations.DeleteModel(
            name='Steward',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='historicalenduser',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalenduser',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
