# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160803_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='status',
            field=models.CharField(choices=[('A', 'The main active bike steward'), ('B', 'A designated back-up steward'), ('I', 'The steward is no longer active'), ('N', 'The user has never been a steward')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='waiver',
            field=models.CharField(choices=[('C', "User's waiver is currently up-to-date."), ('E', 'User must sign new waiver agreement.'), ('N', 'User has not signed a waiver.')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalenduser',
            name='status',
            field=models.CharField(choices=[('A', 'The main active bike steward'), ('B', 'A designated back-up steward'), ('I', 'The steward is no longer active'), ('N', 'The user has never been a steward')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalenduser',
            name='waiver',
            field=models.CharField(choices=[('C', "User's waiver is currently up-to-date."), ('E', 'User must sign new waiver agreement.'), ('N', 'User has not signed a waiver.')], default='N', max_length=1),
        ),
    ]
