# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160803_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='status',
            field=models.CharField(choices=[('A', 'User is the main active bike steward for their fleet'), ('B', 'User is a designated back-up steward'), ('I', 'User is no longer an active steward'), ('N', 'User has never been a steward')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalenduser',
            name='status',
            field=models.CharField(choices=[('A', 'User is the main active bike steward for their fleet'), ('B', 'User is a designated back-up steward'), ('I', 'User is no longer an active steward'), ('N', 'User has never been a steward')], default='N', max_length=1),
        ),
    ]
