
LANDMARK_HEADER = ['OPERATION', 'NWF_ID', 'EXTERNAL_CUSTOMER_ID', 'ICON_NAME', 'LANDMARK_NAME', 'LATITUDE', 'LONGITUDE',
                   'ADDRESS', 'FENCE_RADIUS', 'FENCE_RADIUS_UNITS', 'TYPE', 'LANDMARK_CATEGORY', 'SHOW_ON_OVERVIEW',
                   'LANDMARK_ONLY', 'PRIVATE_USER_ID']
