# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_destination', to='stop.Stop')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction_origin', to='stop.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('holiday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('routes', models.CharField(max_length=12)),
                ('description', models.TextField()),
                ('headway', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('offset', models.IntegerField()),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Joint')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_order', models.IntegerField()),
                ('route', models.IntegerField()),
                ('name', models.CharField(max_length=12)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Direction')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Joint')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StopSeq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=12)),
                ('arrive', models.IntegerField(default=0)),
                ('depart', models.IntegerField(default=0)),
                ('timed', models.IntegerField()),
                ('display', models.IntegerField()),
                ('load_seq', models.IntegerField()),
                ('destination', models.BooleanField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('arrive', models.CharField(max_length=8)),
                ('depart', models.CharField(max_length=8)),
                ('gtfs_depart', models.CharField(max_length=8)),
                ('arrive_24p', models.CharField(max_length=8)),
                ('depart_24p', models.CharField(max_length=8)),
                ('gtfs_depart_24p', models.CharField(max_length=8)),
                ('order', models.IntegerField()),
                ('timepoint', models.IntegerField()),
                ('pickup', models.IntegerField()),
                ('dropoff', models.IntegerField()),
                ('display', models.IntegerField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stop.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.IntegerField()),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='stop.Stop')),
                ('joint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Joint')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='stop.Stop')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_loc', models.IntegerField()),
                ('end_loc', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('driver', models.CharField(max_length=255)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Direction')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='stoptime',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Trip'),
        ),
        migrations.AddField(
            model_name='joint',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='stopseq',
            unique_together=set([('segment', 'load_seq')]),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set([('joint', 'schedule', 'name')]),
        ),
    ]
