# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=12)),
                ('long_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=7)),
                ('text_color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('dir_type', models.CharField(choices=[('I', 'Inbound (return) trip'), ('L', 'Loop (one-direction) trip that returns to trip origin'), ('O', 'Outbound (originating) trip')], max_length=1)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Schedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='direction',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='stopseq',
            name='display',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='direction',
        ),
        migrations.AddField(
            model_name='segment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='direction',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='segment',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Route'),
        ),
        migrations.AlterField(
            model_name='stopseq',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Segment'),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.AddField(
            model_name='segmentorder',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Segment'),
        ),
        migrations.RemoveField(
            model_name='segment',
            name='dir_order',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='joint',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='segmentorder',
            unique_together=set([('schedule', 'order')]),
        ),
    ]
