# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20160919_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopseq',
            name='timed',
            field=models.IntegerField(choices=[(0, 'Times are considered approximate.'), (1, 'Times are considered exact.')]),
        ),
        migrations.RemoveField(
            model_name='stopseq',
            name='destination',
        ),
        migrations.AlterUniqueTogether(
            name='stopseq',
            unique_together=set([('segment', 'arrive')]),
        ),
    ]
