# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20160727_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopseq',
            name='depart',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stopseq',
            name='arrive',
            field=models.IntegerField(default=0),
        ),
    ]
