# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 19:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20160727_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='base_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='joint',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='segment',
        ),
        migrations.AddField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 28, 12, 4, 24, 504701)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
