# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20160728_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together=set([('joint', 'schedule', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='stopseq',
            unique_together=set([('segment', 'load_seq')]),
        ),
    ]
