# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20160920_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='from_stop',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='joint',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='to_stop',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
