# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-28 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_auto_20160728_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stoptime',
            name='arrive',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrive_24p',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='depart',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='depart_24p',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='gtfs_depart',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='gtfs_depart_24p',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.CharField(max_length=255),
        ),
    ]
