# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=12, null=True)),
                ('occupancy', models.IntegerField()),
                ('hov_parking', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating', models.BooleanField()),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vanpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('license', models.CharField(blank=True, max_length=12, null=True)),
                ('occupancy', models.IntegerField()),
                ('hov_parking', models.BooleanField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_friday', to='rideshare.DaySchedule')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_monday', to='rideshare.DaySchedule')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_saturday', to='rideshare.DaySchedule')),
                ('sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_sunday', to='rideshare.DaySchedule')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_thursday', to='rideshare.DaySchedule')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_tuesday', to='rideshare.DaySchedule')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vanpool_wednesday', to='rideshare.DaySchedule')),
            ],
        ),
        migrations.AddField(
            model_name='carpool',
            name='friday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_friday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='monday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_monday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='saturday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_saturday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='sunday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_sunday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='thursday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_thursday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='tuesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_tuesday', to='rideshare.DaySchedule'),
        ),
        migrations.AddField(
            model_name='carpool',
            name='wednesday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_wednesday', to='rideshare.DaySchedule'),
        ),
    ]
